blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name= "blog"

urlpatterns = [
    path('',render_posts, name='posts'),
    path('',render_posts, name='posts2'),
    path("<int:post_id>", post_detail,
         name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings


from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home.html'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

blog/models.py
from django.db import models
import datetime 

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField 


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images/")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
def render_posts(request):
    articulos = Post.objects.all()
    return render(request,'posts.html',
                  {'posts':articulos})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects= Project.objects.all()
    return render(request,'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}

<div class="text-center">
    <h2>{{post.title}}</h2>
<h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>

<img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">

<div class="my-4">
    <p>{{post.description|safe}}</p>
</div>
</div>
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1>POSTS</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" />
    
            </div>
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <h3>{{post.date}}</h3>
                <p>{{post.description|safe|truncatechars:100}}</p>
                <p>{{post.date|date:'z'}} de 365 dias de este año</p>
            
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">Detalle</a>
    
            </div>
        </div>
    
    </div>
</div>
{% endfor %}

{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}

<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portfolio/perfil.png' %}" alt="" width="300" height="300">
    </div>

    <div class="col-md-8 my-auto p-4">
        <h1>I am <strong>Kevin Pico</strong></h1>
        <h3>Information Technology Student</h3>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid tempore temporibus
            aut iusto earum saepe consectetur corrupti ut natus quod, magni nesciunt, adipisci
            distinctio deserunt repellendus eligendi corporis ratione. Modi asperiores aspernatur
            cupiditate minus rem mollitia quisquam, enim dolores corrupti suscipit esse, et aperiam
            quod fuga, ipsa quaerat veniam odit eligendi minima illum! Asperiores modi saepe cumque,
            similique sequi fugit?
        </p>
        <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/cv.pdf' %}" target="_blank">
            Download CV
        </a>
    </div>
</header>

<div class="row my-4 text-center">
    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora, delectus.</p>

    {% for project in projects %}
    <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
            <img src="{{ project.image.url }}" alt="{{ project.title }}" class="card-img-top" width="250" height="300">
            <div class="card-body">
                <p>{{ project.description }}</p>

                <br>
                {% if project.url %}
                <a href="{{ project.url }}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{ project.url }}</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    {% include 'partials/navbar.html' %}
    <h1>HOLA</h1> 
    <div class="container p-4">
        {% block content %}
    
        {% endblock %}

    </div>
    
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Kevin Pico</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">
                Download CV</a>
          </li>
        </ul>

      </div>
    </div>
  </nav>